### ISSUE TITLE
Documentation for `.sub` is missing

### ISSUE THREAD

**Issue by wongjiahau** [KSXGitHub/deno-args#33]
Hi @KSXGitHub, I couldn't find any documentation regarding `.sub` command.

**Comment by KSXGitHub** [comment]
You can see it being used in [the test](https://github.com/KSXGitHub/deno-args/blob/2.0.0/test/wrapper/mixed/setup.ts) and in [the YouTube demo](https://youtu.be/luzgMWrRJxw).

Regarding documentation, I will add soon enough.

**Comment by KSXGitHub** [comment]
[Example](https://github.com/KSXGitHub/deno-args/blob/2.0.2/examples/sub.ts) have been added. Is there anything else you feel missing?
