### ISSUE TITLE
Add value type Boolean

### ISSUE THREAD

**Issue by muuvmuuv** [KSXGitHub/deno-args#35]
Am I missing something or can I not validate Booleans in `Option`?

```ts
    PartialOption('debug', {
      type: Boolean,
      alias: ['n'],
      describe: 'Debug the program.',
      default: false,
    }),
```

**Comment by KSXGitHub** [comment]
Please use [`BinaryFlag`](https://github.com/KSXGitHub/deno-args/blob/2.0.2/lib/flag-types.ts#L105-L119) instead of `PartialOption`. The presence or absent of the flag will be translated to `true` or `false` respectively.

Or are you insisting on `--debug true/false`?

**Comment by muuvmuuv** [comment]
Cool, thank you, wasn't aware of the `BinaryFlag` (and that it is optional). This worked:

```ts
    BinaryFlag('debug', {
      describe: 'Debug the program',
    }),
```
