### ISSUE TITLE
Found an error while using deno cache --reload --unstable

### ISSUE THREAD

**Issue by fzn0x** [KSXGitHub/deno-args#40]
error: Import 'https://deno.land/x/once@0.2.1-ts/index.js' failed: 404 Not Found
Imported from "https://deno.land/x/args@2.0.2/deps.ts:1"

**Comment by KSXGitHub** [comment]
I have fixed this issue in version 2.0.5 but it appears that deno.land/x/ has yet register the latest tags. You may use https://github.com/KSXGitHub/deno-args/raw/2.0.4/lib/wrapper.ts for now.

**Comment by fzn0x** [comment]
> I have fixed this issue in version 2.0.5 but it appears that deno.land/x/ has yet register the latest tags. You may use https://github.com/KSXGitHub/deno-args/raw/2.0.4/lib/wrapper.ts for now.

Thanks bro!

**Comment by KSXGitHub** [comment]
@fauzan121002 You can now use https://deno.land/x/args@2.0.6
