### ISSUE TITLE
How to have global options alongside subcommand options?

### ISSUE THREAD

**Issue by dontlaugh** [KSXGitHub/deno-args#51]
It's unclear how to accomplish this:

```
program --config conf.toml sub1 --sub1-flag foo
program --config conf.toml sub2 --sub2-flag baz
```
... where the `--config` code is shared. Is this possible right now?

**Comment by KSXGitHub** [comment]
I believe the answer is **yes**. It is possible to share options between different subcommands. However, the syntax you gave above won't work: Subcommand name (`sub1`, `sub2`) must immediately follow program name (`program`).

```sh
# wrong
program --config conf.toml sub1 --sub1-flag foo

# right
program sub1 --config conf.toml --sub1-flag foo
```

---

I have just added another example that demonstrates option sharing: https://github.com/KSXGitHub/deno-args/blob/master/examples/share-options-between-subs.ts

**CLI Usage:**

```sh
alias program='deno run https://raw.githubusercontent.com/KSXGitHub/deno-args/master/examples/share-options-between-subs.ts'
program help
program help sub1
program help sub2
program sub1 --shared-opt foo --sub1-opt bar
program sub2 --shared-opt foo --sub2-opt bar
```

In the above example, only `--shared-opt` are shared between `sub1` and `sub2`, `--top-level-opt` is only usable for top level command.
